### ISSUE TITLE
Can not update firmware (using agent)

### ISSUE THREAD

**Issue by bodograumann** [UltimateHackingKeyboard/firmware#147]
I just installed agent 1.2.6 which comes with firmware version 8.4.0. Currently my UHK is running firmware version 8.2.5. I am unable to flash the firmware with agent. Log at the bottom.

Agent requested that I disconnect all USB devices and only reattach the UHK. I did that and after it didn’t work, I even disconnected all the USB headers from the mainboard. Still no improvement.

Please tell me if I can do anything else to figure out this problem.

I am on Gentoo Linux and got agent directly from github HEAD.

`lsusb` output:
```
Bus 011 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 010 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 009 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 008 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 007 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 006 Device 011: ID 1d50:6122 OpenMoko, Inc. 
Bus 006 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Agent flash log:
```
Start flashing firmware
[08:58:26.201] [UhkHidDevice] Available devices unchanged
[08:58:26.203] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"0002:000b:00","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
[08:58:26.203] [UhkHidDevice] USB[W]: 09 
[08:58:26.208] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[08:58:26.208] [DeviceOperation] USB[T]: Read left module version information
[08:58:26.208] [UhkHidDevice] USB[W]: 0e 01 00 
[08:58:26.217] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[08:58:26.218] [DeviceOperation] USB[T]: Read right module version information
[08:58:26.218] [UhkHidDevice] USB[W]: 00 01 
[08:58:26.230] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[08:58:26.230] Device right firmware version: 8.2.5
[08:58:26.230] Device left firmware version: 8.2.5
[08:58:26.231] New firmware version: 8.4.0
[08:58:26.232] [UhkOperations] Operating system: Linux 4.14.44-gentoo x64
[08:58:26.232] [UhkOperations] Start flashing right firmware
[08:58:26.232] [UhkHidDevice] Start reenumeration, mode: Bootloader
[08:58:26.342] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[08:58:26.342] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[08:58:26.811] [UhkHidDevice] reenumeration devices up
[08:58:26.812] [UhkHidDevice] Device communication closing.
[08:58:26.812] [UhkHidDevice] Device communication closed.
[08:58:26.812] [blhost] RUN: /home/nowhereman/Programme/agent/tmp/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[08:58:26.825] [blhost] STDOUT: Error: UsbHidPeripheral() cannot open USB HID device (vid=0x1d50, pid=0x6120, sn=).
[08:58:26.827] [blhost] EXIT_CODE: 1
[08:58:26.827] [blhost] FINISHED: 1
[08:58:26.828] [DeviceService] updateFirmware error { message: 'blhost error code:1',
  stack: 'Error: blhost error code:1\n    at finish (/home/nowhereman/Programme/agent/packages/uhk-agent/dist/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/home/nowhereman/Programme/agent/packages/uhk-agent/dist/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[08:58:26.830] [UhkHidDevice] Available devices:
[08:58:26.831] {"vendorId":7504,"productId":24864,"path":"0002:000c:00","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":0}
[08:58:26.831] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/home/nowhereman/Programme/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:92:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/home/nowhereman/Programme/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /home/nowhereman/Programme/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/home/nowhereman/Programme/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/home/nowhereman/Programme/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/home/nowhereman/Programme/agent/packages/uhk-agent/dist/webpack:/uhk-usb/dist/src/uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)

[08:58:26.832] [blhost] CLOSE_CODE: 1
[08:58:27.336] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
blhost error code:1

**Comment by mondalaci** [comment]
This is weird. It looks as if the firmware update process can't access your UHK. When you first executed Agent, it should have set up udev permissions, so that it can access your UHK. Did you do that step manually by hand and possibly to forgot to include part of the UHK udev file?

A way to test for this is to run Agent as root. If it works then your udev file is most likely incomplete.

**Comment by bodograumann** [comment]
Thanks for your quick reply.

I have taken a closer look at this and found that there is a `rules` directory with a udev rules file. It seems that has to be installed. You should definitely add that information to the Agent Readme, even if the installation would normally happen automatically.

Furthermore I see that you have defined a `SudoService` which uses the `sudo-prompt` package to execute the `setup-rules.sh` install script. As I understand it, this package should call `pkexec`, which has definitely not happened.

Nevertheless I could change keyboard layouts for my UHK perfectly fine. So I guess the udev settings are only required for flashing the firmware!?

I will first try to reinstall Agent to make sure I did not overlook the setup (`git clean -dfx`). Then I will install the udev file manually and see if it works.

**Comment by mondalaci** [comment]
Please use the latest Agent (pre)release, run it as root, try to update the firmware, and let me know your findings.

**Comment by bodograumann** [comment]
Rechecking, there really was no sudo prompt for me.

Then I installed the udev file and confirmed that the device permissions are now set to 0666. So far so good.
Trying to flash the firmware again: still the exact same error message.

Running as root also yields the same result.

What strikes me as odd, is that Agent says:
```[18:36:44.067] [blhost] RUN: /home/nowhereman/Programme/agent/tmp/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605```

But the device id is actually `1d50:6122` instead of `1d50:6120`.

**Comment by bodograumann** [comment]
I’m on udev version 238 if that matters. I’ll also add the relevant dmesg output, maybe that helps:

```
[  706.909054] usb 10-2.4: new full-speed USB device number 14 using xhci_hcd
[  707.007313] hid-generic 0003:1D50:6122.001E: device has no listeners, quitting
[  707.008671] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:15.2/0000:04:00.0/usb10/10-2/10-2.4/10-2.4:1.1/0003:1D50:6122.001F/input/input32
[  707.061155] hid-generic 0003:1D50:6122.001F: input: USB HID v1.10 Keyboard [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:04:00.0-2.4/input1
[  707.062508] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:15.2/0000:04:00.0/usb10/10-2/10-2.4/10-2.4:1.2/0003:1D50:6122.0020/input/input33
[  707.114211] hid-generic 0003:1D50:6122.0020: input: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:04:00.0-2.4/input2
[  707.115477] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:15.2/0000:04:00.0/usb10/10-2/10-2.4/10-2.4:1.3/0003:1D50:6122.0021/input/input34
[  707.167288] hid-generic 0003:1D50:6122.0021: input: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:04:00.0-2.4/input3
[  707.169177] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:15.2/0000:04:00.0/usb10/10-2/10-2.4/10-2.4:1.4/0003:1D50:6122.0022/input/input35
[  707.169265] hid-generic 0003:1D50:6122.0022: input: USB HID v1.10 Mouse [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:04:00.0-2.4/input4

```

**Comment by mondalaci** [comment]
After trying to update the bootloader in Agent, run `dmesg`. Can you see the UHK bootloader showing up in the recent dmesg log entries?

**Comment by bodograumann** [comment]
This is what I get in dmesg when trying to flash the firmware:

```
[ 6872.912351] usb 10-2.4: USB disconnect, device number 14
[ 6873.159564] usb 10-2.4: new full-speed USB device number 15 using xhci_hcd
[ 6873.258371] hid-generic 0003:1D50:6120.0023: device has no listeners, quitting
[ 6877.776490] usb 10-2.4: USB disconnect, device number 15
[ 6877.961535] usb 10-2.4: new full-speed USB device number 16 using xhci_hcd
[ 6878.058551] hid-generic 0003:1D50:6122.0024: device has no listeners, quitting
[ 6878.059926] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:15.2/0000:04:00.0/usb10/10-2/10-2.4/10-2.4:1.1/0003:1D50:6122.0025/input/input36
[ 6878.111624] hid-generic 0003:1D50:6122.0025: input: USB HID v1.10 Keyboard [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:04:00.0-2.4/input1
[ 6878.113048] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:15.2/0000:04:00.0/usb10/10-2/10-2.4/10-2.4:1.2/0003:1D50:6122.0026/input/input37
[ 6878.164660] hid-generic 0003:1D50:6122.0026: input: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:04:00.0-2.4/input2
[ 6878.165974] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:15.2/0000:04:00.0/usb10/10-2/10-2.4/10-2.4:1.3/0003:1D50:6122.0027/input/input38
[ 6878.217625] hid-generic 0003:1D50:6122.0027: input: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:04:00.0-2.4/input3
[ 6878.219443] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:15.2/0000:04:00.0/usb10/10-2/10-2.4/10-2.4:1.4/0003:1D50:6122.0028/input/input39
[ 6878.219629] hid-generic 0003:1D50:6122.0028: input: USB HID v1.10 Mouse [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:04:00.0-2.4/input4
```

I would say the bootloader is `0003:1D50:6122.0020`.

**Comment by mondalaci** [comment]
This is not what you should see. Rather, this is it:

```
[227273.562796] usb 2-9.4.4.4.4: new full-speed USB device number 124 using xhci_hcd
[227273.676011] usb 2-9.4.4.4.4: New USB device found, idVendor=1d50, idProduct=6121
[227273.676014] usb 2-9.4.4.4.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[227273.676016] usb 2-9.4.4.4.4: Product: UHK BusPal Proxy
[227273.676018] usb 2-9.4.4.4.4: Manufacturer: Ultimate Gadget Laboratories
[227273.677696] hid-generic 0003:1D50:6121.0126: hiddev6,hidraw7: USB HID v1.00 Device [Ultimate Gadget Laboratories UHK BusPal Proxy] on usb-0000:00:14.0-9.4.4.4.4/input0
```

What `cat /etc/udev/rules.d/50-uhk60.rules` outputs on your computer?

**Comment by bodograumann** [comment]
I see.

The udev rules were installed successfully as I already said. (I.e. `/etc/udev/rules.d/50-uhk60.rules` is the file from the Agent `rules` directory)

But your dmesg output mentions `hiddev` and `hidraw`. Are you using those?
In that case I would have to enable the `CONFIG_HIDRAW` or `CONFIG_USB_HIDDEV` kernel options.

Any other specific kernel features I need to enable for flashing?
Please also add them to the Readme ;-)

**Comment by mondalaci** [comment]
You see, this is why Linux is immensely problematic. (And this is coming from a devoted Linux user.)

We've been pouring huge resources to Agent to make it work out of the box smoothly, no matter what, and our udev setup procedure is state of the art, and extremely well though out. And then, we hit this issue.

We can't realistically prepare for custom kernels that lack basic USB features. I won't include this to our readme because yours is a one in a thousand case, and I doubt others will face it. We'll rather deal with this in the future by making Agent use a single driver, even for firmware updates. It's planned anyways, but it'll take some time to implement.

1. Can you confirm that the firmware update works with your new kernel?
2. What was the reason you didn't use these kernel options? I assume they're enabled by default.

**Comment by bodograumann** [comment]
1. Yes, I have just bootet the recompiled kernel and now it works :-)

2. It's true that the default value for these options is “yes”, i.e. enabled. My thinking at the time was, all of the usb devices that I have ever used use a driver that's in the kernel, the generic driver in most cases. So they wouldn’t need raw access and it is more secure to disable it. Up until now that assumption was correct.

I can completely understand that my setup is quite specific and this issue will (hopefully) not hit anybody else. I won’t argue whether the used features are basic or unusual.

Anyway, I know that you have enough on your plate as it is and so I really appreciate your help in getting this to work for me. :heart:
Even if you won’t put the information into a trouble shooting guide or FAQ, others can at least find it in this issue. That lets me rest easier.


Apart from the kernel options though, there is a true bug here. Agent should have executed sudo-prompt, which should have called pkexec and installed the udev config. I have no idea why that has not happened for me. pkexec in itself works fine.
It could be that it again only affects me or maybe not so many people with similar setups have actually used the firmware update function.

If you decide to pursue this issue further, I will be at your disposal. Otherwise feel free to close it.

Köszönöm Szépen!

**Comment by mondalaci** [comment]
I'm glad that the firmware update now works for you. Thanks for the quick feedback!

sudo-prompt uses PolicyKit to elevate privileges and looks like it calls `pkexec`. I tested this, and it works fine on my system, and according to my knowledge it should work on other systems too. I'm unsure of why it's not working on your side, and don't know how to debug it. If you figure this out, please do let me know. I'd love to make Agent work smoothly on as many systems as possible.

I'm closing this for the time being because the core issue has been resolved, but feel free to follow up.
