### ISSUE TITLE
make-release.mjs fails to build the firmware

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#908]
```
...
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: build_make//home/laci/projects/firmware-uhk80/uhk/right/src/usb_protocol_handler.o: in function `UsbProtocolHandler':
usb_protocol_handler.c:(.text.UsbProtocolHandler+0x18): undefined reference to `printk'
Memory region         Used Size  Region Size  %age Used
    m_interrupts:          1 KB         1 KB    100.00%
          m_text:      120700 B       463 KB     25.46%
          m_data:       54104 B        64 KB     82.56%
        m_data_2:       58720 B      65280 B     89.95%
        m_noinit:          16 B        255 B      6.27%
collect2: error: ld returned 1 exit status
make: *** [../../scripts/Makedefs.mk:203: build_make/uhk60v1.axf] Error 1
/home/laci/projects/firmware-uhk80/uhk/scripts/node_modules/shelljs/src/common.js:110
  if (config.fatal) throw new Error(logEntry);
                          ^

Error: exec: /home/laci/projects/firmware-uhk80/uhk/right/src/usb_protocol_handler.c: In function 'UsbProtocolHandler':
/home/laci/projects/firmware-uhk80/uhk/right/src/usb_protocol_handler.c:44:5: warning: implicit declaration of function 'printk'; did you mean 'printf'? [-Wimplicit-function-declaration]
   44 |     printk("command %i/n", command);
      |     ^~~~~~
      |     printf
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: build_make//home/laci/projects/firmware-uhk80/uhk/right/src/usb_protocol_handler.o: in function `UsbProtocolHandler':
usb_protocol_handler.c:(.text.UsbProtocolHandler+0x18): undefined reference to `printk'
collect2: error: ld returned 1 exit status
make: *** [../../scripts/Makedefs.mk:203: build_make/uhk60v1.axf] Error 1

    at Object.error (/home/laci/projects/firmware-uhk80/uhk/scripts/node_modules/shelljs/src/common.js:110:27)
    at execSync (/home/laci/projects/firmware-uhk80/uhk/scripts/node_modules/shelljs/src/exec.js:120:12)
    at Object._exec (/home/laci/projects/firmware-uhk80/uhk/scripts/node_modules/shelljs/src/exec.js:223:12)
    at Object.exec (/home/laci/projects/firmware-uhk80/uhk/scripts/node_modules/shelljs/src/common.js:335:23)
    at build (file:///home/laci/projects/firmware-uhk80/uhk/scripts/make-release.mjs:27:19)
    at file:///home/laci/projects/firmware-uhk80/uhk/scripts/make-release.mjs:68:5
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.14.0
```

**Comment by kareltucek** [comment]
Pushed fix into master.
